/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TravelerRouteImport } from './routes/traveler'
import { Route as SignupTravelerRouteImport } from './routes/signupTraveler'
import { Route as SignupDriverRouteImport } from './routes/signupDriver'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackingIdRouteImport } from './routes/tracking.$id'
import { Route as TravelerTicketIdRouteImport } from './routes/traveler.ticket.$id'
import { Route as TravelerPaymentIdRouteImport } from './routes/traveler.payment.$id'
import { Route as TravelerBookingIdRouteImport } from './routes/traveler.booking.$id'

const TravelerRoute = TravelerRouteImport.update({
  id: '/traveler',
  path: '/traveler',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupTravelerRoute = SignupTravelerRouteImport.update({
  id: '/signupTraveler',
  path: '/signupTraveler',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupDriverRoute = SignupDriverRouteImport.update({
  id: '/signupDriver',
  path: '/signupDriver',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingIdRoute = TrackingIdRouteImport.update({
  id: '/tracking/$id',
  path: '/tracking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelerTicketIdRoute = TravelerTicketIdRouteImport.update({
  id: '/ticket/$id',
  path: '/ticket/$id',
  getParentRoute: () => TravelerRoute,
} as any)
const TravelerPaymentIdRoute = TravelerPaymentIdRouteImport.update({
  id: '/payment/$id',
  path: '/payment/$id',
  getParentRoute: () => TravelerRoute,
} as any)
const TravelerBookingIdRoute = TravelerBookingIdRouteImport.update({
  id: '/booking/$id',
  path: '/booking/$id',
  getParentRoute: () => TravelerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/driver': typeof DriverRoute
  '/login': typeof LoginRoute
  '/signupDriver': typeof SignupDriverRoute
  '/signupTraveler': typeof SignupTravelerRoute
  '/traveler': typeof TravelerRouteWithChildren
  '/tracking/$id': typeof TrackingIdRoute
  '/traveler/booking/$id': typeof TravelerBookingIdRoute
  '/traveler/payment/$id': typeof TravelerPaymentIdRoute
  '/traveler/ticket/$id': typeof TravelerTicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/driver': typeof DriverRoute
  '/login': typeof LoginRoute
  '/signupDriver': typeof SignupDriverRoute
  '/signupTraveler': typeof SignupTravelerRoute
  '/traveler': typeof TravelerRouteWithChildren
  '/tracking/$id': typeof TrackingIdRoute
  '/traveler/booking/$id': typeof TravelerBookingIdRoute
  '/traveler/payment/$id': typeof TravelerPaymentIdRoute
  '/traveler/ticket/$id': typeof TravelerTicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/driver': typeof DriverRoute
  '/login': typeof LoginRoute
  '/signupDriver': typeof SignupDriverRoute
  '/signupTraveler': typeof SignupTravelerRoute
  '/traveler': typeof TravelerRouteWithChildren
  '/tracking/$id': typeof TrackingIdRoute
  '/traveler/booking/$id': typeof TravelerBookingIdRoute
  '/traveler/payment/$id': typeof TravelerPaymentIdRoute
  '/traveler/ticket/$id': typeof TravelerTicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/driver'
    | '/login'
    | '/signupDriver'
    | '/signupTraveler'
    | '/traveler'
    | '/tracking/$id'
    | '/traveler/booking/$id'
    | '/traveler/payment/$id'
    | '/traveler/ticket/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/driver'
    | '/login'
    | '/signupDriver'
    | '/signupTraveler'
    | '/traveler'
    | '/tracking/$id'
    | '/traveler/booking/$id'
    | '/traveler/payment/$id'
    | '/traveler/ticket/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/driver'
    | '/login'
    | '/signupDriver'
    | '/signupTraveler'
    | '/traveler'
    | '/tracking/$id'
    | '/traveler/booking/$id'
    | '/traveler/payment/$id'
    | '/traveler/ticket/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DriverRoute: typeof DriverRoute
  LoginRoute: typeof LoginRoute
  SignupDriverRoute: typeof SignupDriverRoute
  SignupTravelerRoute: typeof SignupTravelerRoute
  TravelerRoute: typeof TravelerRouteWithChildren
  TrackingIdRoute: typeof TrackingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/traveler': {
      id: '/traveler'
      path: '/traveler'
      fullPath: '/traveler'
      preLoaderRoute: typeof TravelerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signupTraveler': {
      id: '/signupTraveler'
      path: '/signupTraveler'
      fullPath: '/signupTraveler'
      preLoaderRoute: typeof SignupTravelerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signupDriver': {
      id: '/signupDriver'
      path: '/signupDriver'
      fullPath: '/signupDriver'
      preLoaderRoute: typeof SignupDriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking/$id': {
      id: '/tracking/$id'
      path: '/tracking/$id'
      fullPath: '/tracking/$id'
      preLoaderRoute: typeof TrackingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traveler/ticket/$id': {
      id: '/traveler/ticket/$id'
      path: '/ticket/$id'
      fullPath: '/traveler/ticket/$id'
      preLoaderRoute: typeof TravelerTicketIdRouteImport
      parentRoute: typeof TravelerRoute
    }
    '/traveler/payment/$id': {
      id: '/traveler/payment/$id'
      path: '/payment/$id'
      fullPath: '/traveler/payment/$id'
      preLoaderRoute: typeof TravelerPaymentIdRouteImport
      parentRoute: typeof TravelerRoute
    }
    '/traveler/booking/$id': {
      id: '/traveler/booking/$id'
      path: '/booking/$id'
      fullPath: '/traveler/booking/$id'
      preLoaderRoute: typeof TravelerBookingIdRouteImport
      parentRoute: typeof TravelerRoute
    }
  }
}

interface TravelerRouteChildren {
  TravelerBookingIdRoute: typeof TravelerBookingIdRoute
  TravelerPaymentIdRoute: typeof TravelerPaymentIdRoute
  TravelerTicketIdRoute: typeof TravelerTicketIdRoute
}

const TravelerRouteChildren: TravelerRouteChildren = {
  TravelerBookingIdRoute: TravelerBookingIdRoute,
  TravelerPaymentIdRoute: TravelerPaymentIdRoute,
  TravelerTicketIdRoute: TravelerTicketIdRoute,
}

const TravelerRouteWithChildren = TravelerRoute._addFileChildren(
  TravelerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DriverRoute: DriverRoute,
  LoginRoute: LoginRoute,
  SignupDriverRoute: SignupDriverRoute,
  SignupTravelerRoute: SignupTravelerRoute,
  TravelerRoute: TravelerRouteWithChildren,
  TrackingIdRoute: TrackingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
